### PR TITLE
add how-to guides

### PR DESCRIPTION
**Pull request by danshapero**
A few people have asked for learning material that covers more advanced topics -- things for when you already know how to use the package and now want to do more serious modeling with it. This patch adds a how-to guide on checkpointing and another one on optimizing performance by choosing different nonlinear solver options. More to follow.

### CODE REVIEW

**Review by jabadge — CHANGES_REQUESTED** [review]
Thanks for making these demos! I think they'll be super helpful for folks working on more complex projects with icepack. I ran into some non-linear divergence errors. I'm not sure if they are specific to my setup or if other users are likely to experience these same errors.

For the performance demo, running the simulation with the default solver worked fine, but running the simulation with the fast and faster solver threw this error:

ConvergenceError: Nonlinear solve failed to converge after 0 nonlinear iterations.
Reason:
   DIVERGED_FNORM_NAN

I run into this same error in the checkpointing demo. Switching to the default solver options works for the first spin-up stage, but not the second. In the second spin-up stage, I get this similar error:

ConvergenceError: Nonlinear solve failed to converge after 50 nonlinear iterations.
Reason:
   DIVERGED_MAX_IT

I found one typo in the performance demo, which I've corrected in bold: "There are two types of diagnostic solvers; a hand-written Newton line search procedure **implemented** in icepack, and one that calls out to PETSc's scalable nonlinear equation solver or SNES. First, we'll create a solver using the icepack routines as a performance baseline. To solve the linear systems that define the search direction, we'll use a direct factorization method."

**Comment by danshapero** [comment]
Hah and this is why we have code reviews! :D I'll see if I can reproduce the convergence failures. You're on MacOS Catalina and Python-3.8 right? I think it's more likely that input data lead to bad intermediate states, like with a perilously low strain rate, not that there's something wrong with your system.

**Comment by jabadge** [comment]
I'm on MacOS Mojave (10.14.6) and Python 3.8.5 in my firedrake environment.

**Comment by jabadge** [comment]
Both of the new demos now work for me. The text also looks good overall. Just one comment for 01-performance is that the third sentence in the first paragraph of the conclusion doesn't make sense.

**Comment by danshapero** [comment]
Gotcha, I changed it to a link to the PETSc documentation. Thanks for the feedback!

**Pull request merged**
